title: Irvin's GitHub Pages
email: 
description: Man's search for meaning.. of Technology
url: "https://irvinleegc.github.io/"
baseurl:

twitter_username: _irvinleegc_
github_username:  irvinleegc
linkedin_username: irvinlee
disqus-shortname: irvinleegc-github-io
google_analytics: UA-93472024-1

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  
gems:
  - jemoji
